name: Spellcheck

on: workflow_dispatch

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install LanguageTool
      run: |
        wget https://languagetool.org/download/LanguageTool-stable.zip
        unzip LanguageTool-stable.zip -d LanguageTool
        ls -l LanguageTool

    - name: Find Markdown files
      id: find_files
      run: |
        echo "files=$(find . -name '*.md' -print | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Pre-process Markdown files
      run: |
        for file in $files; do
          sed '/^```/,/^```/d' "$file" > "processed_$file"
        done
      env:
        files: ${{ env.files }}

    - name: Run LanguageTool
      run: |
        for file in $files; do
          java -jar LanguageTool/LanguageTool-6.5/languagetool-commandline.jar -l en-US "processed_$file" >> languagetool_output.txt
        done
      env:
        files: ${{ env.files }}

    - name: Create GitHub Issue
      if: always()
      uses: JasonEtco/create-an-issue@v2
      with:
        title: "LanguageTool Spellcheck Report"
        body: |
          The following issues were found during the spellcheck:
          ```
          ${{ steps.run_languagetool.outputs.languagetool_output }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
