name: Spellcheck

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install LanguageTool
      run: |
        wget https://languagetool.org/download/LanguageTool-stable.zip
        unzip LanguageTool-stable.zip -d LanguageTool
        ls -l LanguageTool

    - name: Find Markdown files
      id: find_files
      run: |
        echo "::set-output name=files::$(find . -name '*.md' -print | tr '\n' ' ')"

    - name: Run LanguageTool
      run: |
        for file in ${{ steps.find_files.outputs.files }}; do
          java -jar LanguageTool/LanguageTool-6.5/languagetool-commandline.jar -l en-US "$file"
        done
